# Site settings
title:          HyeongJu
description:    Web Devloper. HyeongJu
baseurl:        ''
url:            https://hyeongjukim.github.io
name:           HyeongJu
timezone:       Asia/Seoul
locale:         ko-KR
repository:     hyeongjukim.github.io

# Google Analytics
google_analytics: UA-153225361-1

# Author
author:
  name:         HyeongJu
  url:          https://hyeongjukim.github.io
  email:        hjkim880527@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
# - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         hyeongjukim
